src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Inventory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inventory Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inventory Managers</relationshipLabel>
        <relationshipName>Inventory_Managers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Computer_Inventory_items__c</fullName>
        <label>Number Computer Inventory items</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_amount_of_Computer_Inventory_items__c</fullName>
        <label>Total amount of Computer Inventory items</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Computer_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Computer Inventories</relationshipLabel>
        <relationshipName>Contact_Persons</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Computer Inventories</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Computer Inventory</label>
    <nameField>
        <label>Computer Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Computer Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ComputerInventoryTriggerHandler.cls
public class ComputerInventoryTriggerHandler {
    
    public static void putContactPerson(List<Computer_Inventory__c> computerInventoryList){
        List<Id> idList=new List<Id>();
        for(Computer_Inventory__c computerInventory:computerInventoryList ){
            idList.add(computerInventory.Customer__c);
        }
        
        List<Account> accList = [SELECT Id,
                                 Inventory_Manager__c
                                 FROM Account
                                 WHERE Id IN:idList];
        
        for(Computer_Inventory__c computerInventory:computerInventoryList ){
            for(Account acc:accList){
                if(computerInventory.Customer__c==acc.Id){
                    computerInventory.Contact_Person__c = acc.Inventory_Manager__c;
                }
            }	
        }
    }
    
    public static void accNumberAndTotalAmount(List<Computer_Inventory__c> computerInventoryList){
        List<Id> accIds = new List<Id>();
        List<Account> updateAccList =new List<Account>();
        for(Computer_Inventory__c computerInventory:computerInventoryList ){
            accIds.add(computerInventory.Customer__c);
        }
        List<Account> accList = [SELECT Id, 	
                                 Number_Computer_Inventory_items__c,
                                 Total_amount_of_Computer_Inventory_items__c,
                                 (Select Id, Value__c From Customers__r)
                                 FROM Account
                                 WHERE Id IN:accIds];
        for (Account acc: accList){
            
            acc.Number_Computer_Inventory_items__c=acc.Customers__r.size();
            acc.Total_amount_of_Computer_Inventory_items__c=0;
            for(Computer_Inventory__c compInventory:acc.Customers__r ){
                if(compInventory.Value__c!=null){
                    acc.Total_amount_of_Computer_Inventory_items__c+=compInventory.Value__c;
                }
            }
            updateAccList.add(acc);
        }
        update updateAccList;
    }
    public static void accNumberAndTotalAmountAfterDelete(List<Computer_Inventory__c> computerInventoryList){
        accNumberAndTotalAmount(computerInventoryList);  
    }
}